name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.36.8
  permission_handler: ^11.3.1
  location: ^6.0.0
  logger: ^2.0.2
  wifi_scan: ^0.4.1+2
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.2
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/icons/dashboard.png
    - assets/icons/edit.png
    - assets/icons/configuraciones.png
    - assets/icons/history.png
    - assets/icons/devices.png
    - .env
    - .env.example

